### ISSUE TITLE
Missing fuzzyClustering.txt

### ISSUE THREAD

**Issue by deric** [wiwie/clusteval#11]
`TestClustering` requires a `fuzzyClustering.txt` file which is not present in any repository (nor VirtualBox image).
```
testCaseRepository/results/01_30_2013-21_31_25_tc_vs_DS1/clusters/fuzzyClustering.txt
```

**Comment by wiwie** [comment]
checked in missing files into the dev branch. please give it another shot.

**Comment by wiwie** [comment]
no comments since March; assume this one is resolved.
