### ISSUE TITLE
PostgreSQL Permission Error (and fix)

### ISSUE THREAD

**Issue by bmuchmore** [wiwie/clusteval#2]
If you see the following when starting up...

web_1    | Starting PostgreSQL 9.4 database server: mainThe PostgreSQL server failed to start. Please check the log output: 2015-11-12 09:36:06 UTC [23-1] FATAL: could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied ... failed!
web_1    |  failed!

Go into the wiwiec/clustevalwebsite docker image using, for example, the following bash command...

docker run -it wiwiec/clustevalwebsite /bin/bash

Then once inside the docker image run the following...

mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private

Now, open a new terminal and commit the change you just made to the wiwiec/clustevalwebsite image...

docker commit **INSERT CONTAINER ID HERE** wiwiec/clustevalwebsite

By the way, you can find the container id of the running wiwiec/clustevalwebsite image with...

docker ps -a

Now, everything should work when you run...

docker-compose up

And you navigate to 127.0.0.1:3000

Hope that helps.

-Brian Muchmore

**Comment by wiwie** [comment]
going to close it, as you are also providing a fix.
weirdly I'm not encountering the issue on any of my machines though.

**Comment by bmuchmore** [comment]
My impression is that it is a docker-related issue, so my guess is that it
is system/docker version specific.
